rails-crud-master/config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items do#, except: :index
   resources :comments, only: [:create, :destroy]
  end
  devise_for :users
  
  # get '/items' => 'items#items'
  # get '/items/new' => 'items#new'
  # post '/create' => 'items#create'
  # get '/items/:item_id' => 'items#show'
  # get '/items/:item_id/edit' => 'items#edit'
  # post '/items/update/:item_id' => 'items#update'
  # get '/items/:item_id/delete' => 'items#delete'
end

rails-crud-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

rails-crud-master/app/models/item.rb
class Item < ActiveRecord::Base
    has_many :comments, dependent: :destroy
end

rails-crud-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments, dependent: :destroy
end

rails-crud-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    added_columns = [:username, :age, :bdate]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_columns)
    devise_parameter_sanitizer.permit(:account_update, keys: added_columns)
  end
end

rails-crud-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :load_item
    
    def create
        @user = current_user
        @comment = Comment.new(comment_params)
        @comment.user = @user
        @comment.item = @item
        @comment.save
    end
    
    def destroy
    end
    
    private
    def comment_params
        params.require(:comment).permit(:body)
    end
    
    def load_item
        @item = Item.find params[:item_id]
    end
end

rails-crud-master/app/controllers/items_controller.rb
class ItemsController < ApplicationController
    # before_action :authenticate_user!
    before_action :load_item, only: [:show, :edit, :update, :destroy]
    
    # item 목록 페이지
    def index
        @items = Item.all
    end
    
    # item 생성 페이지
    def new
        @item = Item.new
    end
    
    # item 생성 액션
    def create
        @item = Item.new(set_params)
        @item.save
        redirect_to root_path
    end
    
    # item 상세보기 페이지
    def show
        @comments = Comment.where(item: @item)
    end
    
    # item 수정 페이지
    def edit
    end
    
    # item 수정 액션
    def update
        @item.update(set_params)
        redirect_to item_path(@item)
    end
    
    # item 삭제 액션
    def destroy
        @item.destroy
        redirect_to root_path
    end
    
    private
    def load_item
        @item = Item.find params[:id]
    end
    
    def set_params
        params.require(:item).permit(:title, :price, :description)
    end
end

rails-crud-master/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-crud-master/app/helpers/comments_helper.rb
module CommentsHelper
end

rails-crud-master/app/helpers/items_helper.rb
module ItemsHelper
end

rails-crud-master/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <label>상품이름</label><br>
  <%= f.text_field :title %><br><br>
  
  <label>상품가격</label><br>
  <%= f.number_field :price %><br><br>
  
  <label>상품설명</label><br>
  <%= f.text_area :description, size: "60x12" %><br><br>
  
  <%= f.submit "저장" %>
<% end %>

rails-crud-master/app/views/items/edit.html.erb
<div class="container">
  <%= render "form" %>
</div>

rails-crud-master/app/views/items/index.html.erb
<div class="row container">
    <% @items.each do |item| %>
    <div class="card col-4" style="width: 18rem;">
        <!--<img src="..." class="card-img-top" alt="...">-->
        <div class="card-body">
            <h5 class="card-title"><%= item.title %></h5>
            <p class="card-text"><%= item.price %>원</p>
            <a href="/items/<%= item.id %>" class="btn btn-primary">보러가기</a>
        </div>
    </div>
    <% end %>
</div>

rails-crud-master/app/views/items/new.html.erb
<div class="container">
  <%= render "form" %>
</div>

rails-crud-master/app/views/items/show.html.erb
<div class="container">
    <div class="row">
      <div class="card col-4" style="width: 18rem;">
      <!--<img src="..." class="card-img-top" alt="...">-->
      <div class="card-body">
          <h5 class="card-title"><%= @item.title %></h5>
          <p class="card-text">가격 : <%= @item.price %>원</p>
          <p class="card-text"><%= @item.description %></p>
          <a href="/items/<%= @item.id %>/edit" class="btn btn-primary">수정하기</a>
          <%= link_to "삭제하기", item_path(@item), method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
    </div>
    <br>
    
    <%= form_for(Comment.new, url: item_comments_path(@item), remote: true) do |f| %>
      <%= f.label :body %><br>
      <%= f.text_area :body, id: "comment-body" %><br><br>
      <%= f.submit "댓글 작성" %>
    <% end %>
    
    <ul id="comments">
      <% @comments.each do |comment| %>
        <%= render comment %>
      <% end %>
    </ul>
</div>

rails-crud-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => "off" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/items">멋사 쇼핑몰</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "회원정보수정", edit_user_registration_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "로그인", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "회원가입", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item active">
            <a class="nav-link" href="/items/new">상품생성하기</a>
          </li>
        </ul>
      </div>
    </nav>

<%= yield %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>